services:
  evolution-api:
    container_name: evolution-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - evolution-redis
      - evolution-postgres
    ports:
      - 8080:8080
    volumes:
      - evolution-instances:/evolution/instances
    networks:
      - chatwoot-evolution-network
    env_file:
      - .env
    expose:
      - 8080

  evolution-redis:
    image: redis:latest
    container_name: evolution-redis
    restart: always
    networks:
      - chatwoot-evolution-network
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution-redis:/data
    ports:
      - 6379:6379

  evolution-postgres:
    container_name: evolution-postgres
    image: postgres:15
    networks:
      - chatwoot-evolution-network
    command: [ "postgres", "-c", "max_connections=1000" ]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - evolution-postgres:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  evolution-instances:
  evolution-redis:
  evolution-postgres:


networks:
  chatwoot-evolution-network:
    external: true
